<?php

namespace App\Models;

use App\Traits\Image;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Languages extends Model
{
    use  Image;

    protected static $configs = [
            'model' => 'App\Models\Languages',
            'images' => [
                'default' => [
                    'title' => 'image to default',
                    'path' => 'images\languages\\'
                ]
            ]
        ];
    protected $casts
        = [

        ];

    public static function _save($data, $model = false)
    {

        if (!$model) {
            $model = new self();
        }

        $model->name = $data['name'];
        $model->slug = $data['slug'];
        $model->status = (boolean) $data['status'];
        $model->static = (boolean) $data['static'];

        if ($model->save()) {
            if ($model->static) {
                self::query()->where([['static', 1], ['id', '<>', $model->id]])
                    ->update(['static' => 0]);
            }
            if (isset($data['image'])) {
                $model->saveImage($data['image']);
            }
        }
        return $model;
    }

    public function save(array $options = [])
    {
        Cache::forget('static_language_slug');
        Cache::forget('languages');
        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public static function GetStaticSlug()
    {

        $slug = Cache::rememberForever('static_language_slug', function () {
            if (($slug = self::query()->where([['status', 1], ['static', 1]])
                ->get('slug'))
            ) {
                $slug = self::query()->where([['static', 1]])->first('slug');
            }
            return $slug->slug;
        });
        return $slug;
    }


    public function getImageAttribute(){
        $image = \App\Models\Image::query()->where([['model',self::$configs['model']],['item_id',$this->id]])->first();
        return $image?self::$configs['images']['default']['path'] . $image->name:null;
    }

}
